make sure Terraform E2E test fails on detected changes

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -48,7 +48,12 @@ jobs:
         env:
           BETTERUPTIME_API_TOKEN: ${{ secrets.UPTIME_E2E_TEAM_TOKEN }}
       - name: Plan resources via Terraform - must be empty
-        run: make terraform CONFIGURATION="${{ matrix.config }}" ARGS="plan --detailed-exitcode --input=false"
+        run: |
+          make terraform CONFIGURATION="${{ matrix.config }}" ARGS="plan --detailed-exitcode --input=false"
+          if [ $? -eq 2 ]; then
+            echo "Terraform plan has changes, exiting with error."
+            exit 1
+          fi
         env:
           BETTERUPTIME_API_TOKEN: ${{ secrets.UPTIME_E2E_TEAM_TOKEN }}
       - name: Destroy resources via Terraform
